### ISSUE TITLE
[iOS] Exceptions Missing DebugSymbols and LineNumbers

### ISSUE THREAD

**Issue by ArnauKokoro** [getsentry/sentry-unity#1131]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
0.27.0

How did you install the package? 
Git-URL

Which version of Unity?
2020.3.15.f2

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
iOS [BITCODE DISABLED] for Xcode 14

### Steps to Reproduce

1. Invoke an Exception

### Expected Result

[iOS] DebugSymbols and LineNumbers shown on the sentry exception event

### Actual Result

[iOS] DebugSymbols and LineNumbers are not shown [BITCODE DISABLED]
[Android] DebugSymbols and LineNumbers are SHOWN

### Comments
Android and iOS DebugSymbols are uploaded on build phase.

### Any logs or screenshots

<img width="1086" alt="Captura de Pantalla 2022-12-27 a las 14 18 01" src="https://user-images.githubusercontent.com/80262126/209676967-0cd635e7-d736-44d5-b2f8-ae425a8c57e0.png">

**Comment by bitsandfoxes** [comment]
On Android, it works but the same build on iOS has the line numbers missing?
Do you see any errors in the build log? There should be a build phase `Run custom shell script 'Symbol Upload'`.
Additionally, could you provide the SentryCLI logs? You can find them in the same directory as the Xcode project named `sentry-symbols-upload.log`.

**Comment by ArnauKokoro** [comment]
On Android I can see the symbolic file on the sentry exception event and the line number. But the same version and build on iOS I cannot see file or line number. I don't see error on build log and I can see the symbolic file uploaded after build is successful and running on the iphone. On _sentry-symbols-upload.log_ I can see all the libraries I use on PENDING state but as I said after build success I can see all the libraries uploaded.

**Comment by ArnauKokoro** [comment]
@bitsandfoxes ¿Any change on this?

**Comment by bitsandfoxes** [comment]
Sorry, I must have missed your reply, thanks for reaching out again.
Can you share the link to the event with me? stefan@sentry.io

**Comment by bitsandfoxes** [comment]
Thanks. Taking a look at those events I think you're doing everything correctly and I noticed 2 things:
1. Some issues are due to being `UnobservedTaskException`: This was fixed in https://github.com/getsentry/sentry-dotnet/pull/2067 and is part of the `0.28.0` release
2. Issues that fall not into 1. always seem to reference `Gameassebly.fallback`. This happens when Unity does not provide us with an actual ImageName from where the issue comes from. Unfortunately, there is nothing that I can see that we can do in those cases.
The IL2CPP line number support does improve with newer Unity versions. So it's possible that if you were to upgrade from 2020 to 2021 you'd see an improvement in stacktrace quality too.

Sorry to not being able to help/fix this in a more satisfying manner.
