### ISSUE TITLE
Can not configure for using PROXY

### ISSUE THREAD

**Issue by KSerjyk** [getsentry/sentry-unity#1134]
### Environment
UNITY

Which version of the SDK?
0.27.0
How did you install the package? (Git-URL, Assetstore)
GIT-URL

Which version of Unity?
2021.3.4f1
Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Tested only EDITOR
### Steps to Reproduce

1. Set DSN and proxy(SentryOptions)
2. Set proxy to DSN
3. Set no DSN only proxy

### Expected Result
Send data via proxy

### Actual Result
Sending via DSN. It is closed from world, so we are getting errors.

**Comment by bitsandfoxes** [comment]
> * Set DSN and proxy(SentryOptions)
> * Set proxy to DSN
> * Set no DSN only proxy

Hey @KSerjyk! Sorry to see you run into an issue. Can you clarify what you mean by this? Is this all part of the `Configure`-Callback? Do you let the SDK self-initialize or are you initializing Sentry from code?

**Comment by KSerjyk** [comment]
1. We tried self-initialize with setting DSN real address and proxy(got error no public key no port specified)
2. We tried from code enabling/disabling sentry in inspector, filling(with real/proxy address(in case of proxy got error no public key no port specified)) and not filling(got error that no DSN provided) DSN


![Sentry](https://user-images.githubusercontent.com/45832971/210568371-704d9c12-4119-4aef-b786-ecd8e6e53023.png)
![Sentry2](https://user-images.githubusercontent.com/45832971/210568378-da00990c-0ae6-46c4-932e-6cbbba12e877.png)
![Sentry3](https://user-images.githubusercontent.com/45832971/210568380-62e54756-e310-4101-93ba-396e263c27e1.png)
![Sentry4](https://user-images.githubusercontent.com/45832971/210568383-2581f472-18b3-4f89-8581-387617263e5a.png)

**Comment by mattjohnsonpint** [comment]
Hi @KSerjyk.  The only thing we do with the `HttpProxy` option is [pass it along](https://github.com/getsentry/sentry-dotnet/blob/af8c42c049e3dc4fba23be60b462583b7ae015ff/src/Sentry/Internal/Http/DefaultSentryHttpClientFactory.cs#L23-L28) to .NET's [`HttpClientHandler.Proxy`](https://learn.microsoft.com/dotnet/api/system.net.http.httpclienthandler.proxy) property.  That handler is used by the internal `HttpClient` that sends data to the Sentry endpoint specified in the DSN.

> Problem is that our sentry server is accessed via VPN only and we have proxy server that redirects logs to our server

I could be mistaken, but it doesn't sound like this is the typical use case for an HTTP proxy server.  Typically one uses such a server for *outbound* requests within a protected network.  It sounds to me like you are trying to expose a publicly accessible proxy server that forwards *inbound* requests to elsewhere on your network where you are self-hosting Sentry.  Is that correct?  If so, what type of proxy server are you using?

Have you validated that you can make other requests using it outside of your game? For example, if you configure a computer on the public Internet to use your proxy server, can you then make regular HTTP and HTTPS requests from a browser (or curl, etc.) to the Sentry server within your network?

I'm not saying an inbound proxy won't work, I'm just saying that's not the typical use case for a proxy server.  Rather than proxy, you might consider setting up port forwarding on your network to expose the endpoint to the Internet.

Alternatively, if you wanted a more robust solution, you could expose an instance of [Sentry Relay](https://docs.sentry.io/product/relay/).

**Comment by mattjohnsonpint** [comment]
Another perhaps more useful test would be to make a small .NET console app using the Sentry .NET SDK directly and supply your proxy server and DSN there, calling something like `SentrySdk.CaptureMessage("test");`.  Try it from outside your network.  If the message shows up in your Sentry issues, then we know that the network is configured correctly and can focus on the Unity side of things.  If it doesn't show up, then the issue is with your network, proxy, or Sentry configuration.

**Comment by KSerjyk** [comment]
Our application is crossplatform, it should work on Android, iOS, MAC OS, Windows, Linux, WEB GL.
According to your last comment, it will be better to use Sentry Relay. Does it work on all platforms we need? Is there version for Unity of Sentry Relay? If not, will DLL from nuget work on needed platforms?

**Comment by mattjohnsonpint** [comment]
Sorry if I confused the issue with the SDK part.  Sentry Relay is for the server side.  It has no impact on what you do on the SDK side in your application.  You would still use the regular Unity SDK, supporting all platforms.

Assuming you are self-hosting (running your own Sentry server), you will still need to expose an HTTPS endpoint to the public Internet for your application to communicate with.  That's port forwarding configuration on the firewall, not a proxy server.  If you use Relay, then forward to the instance of Relay you are running.  If you aren't using Relay, then forward directly to your instance of the Sentry server you are running.

Of course you can avoid all of that by using the hosted Sentry SaaS offering instead.

**Comment by mattjohnsonpint** [comment]
To clarify the part about the SDK support, the Sentry Unity SDK bundles several of the other Sentry SDKs to handle things like native crashes.  Generally, you don't need to worry about that.  However, if you rely on setting a proxy server to communicate to your Sentry host - then that particular part wouldn't be conveyed to the native SDK for iOS, and thus you wouldn't be capturing native exception on iOS.   This only applies if you are relying on setting a proxy server via the `HttpProxy` option in your code.

You might be wondering about when the `HttpProxy` setting would be used at all.  Typically it isn't used by games or applications that are distributed to the general public, but rather set on servers that are running back-end processes.  For example, if you were hosting an ASP.NET Core application in your network, and your network was configured to block all outbound communication unless it went through a proxy server on your network, then you would set the proxy server's address and credentials in the `HttpProxy` option.

The only reason it appears in Unity at all is because the Unity SDK is built on top of the .NET SDK, which is serving many different types of applications.

I don't recommend using the `HttpProxy` setting for any game or application that is distributed to the general public or will otherwise be running across the Internet.

**Comment by bitsandfoxes** [comment]
I hope this works out for you and if you need further assistance please feel free to reach out again! :)
