### ISSUE TITLE
Is there a way to distinguish Debug.LogException(...) and throw Exception?

### ISSUE THREAD

**Issue by EAdemov** [getsentry/sentry-unity#1200]
Hey guys. Thanks for the great work with the Unity SDK!
I noticed that Sentry catches:
`Debug.LogException(new Exception(...));`
and 
`throw new Exception(...);`
and logs each in the Dashboard. We have couple places where we want to log the exception in the console but prevent it from logging in the dashboard. I was wondering if this possible?
Another side note is that `Debug.LogError(...);` seems like a log that Sentry tracks in the dashboard. Is there a way to prevent this, since some 3rd party libraries we use got that log type and it pretty much spamming out dashboard for no reason?

**Comment by mattjohnsonpint** [comment]
I believe this is a known limitation.
https://docs.sentry.io/platforms/unity/troubleshooting/#unhandled-exceptions---debuglogexception

**Comment by bitsandfoxes** [comment]
Since the SDK can't distinguish between `throw new Exception` and `Debug.LogException` your best option is the [`beforeSend`](https://docs.sentry.io/platforms/dotnet/configuration/filtering/#filtering-error-events) callback.
You can add the filter to the scriptable object options configuration.

Regarding the `Debug.LogError`: That's still our TODO https://github.com/getsentry/sentry-unity/issues/60
As a workaround you could add your own LogHandler in between Unity and the SDK. 
That should happen after the SDK has initialized, so if `Awake` is early enough for you then that should work.
Something like this should work:
```
public class EAdemovLogHandler : ILogHandler
{
    private ILogHandler _sentrySdkLogHandler;

    public EAdemovLogHandler()
    {
        _sentrySdkLogHandler = Debug.unityLogger.logHandler;
        Debug.unityLogger.logHandler = this;
    }

    public void LogFormat(LogType logType, Object context, string format, params object[] args)
    {
        if (logType == LogType.Error)
        {
            // Here your filtering
        }

        _sentrySdkLogHandler.LogFormat(logType, context, format, args);
    }

    public void LogException(Exception exception, Object context)
        => _sentrySdkLogHandler.LogException(exception, context);
}
```

**Comment by EAdemov** [comment]
Hey. Thanks for the suggestion. I ended up with my own ILogHandler to ignore Error.

**Comment by bitsandfoxes** [comment]
Sure thing! Glad it worked out.
I'm going to close this in favour of the one tracking the feature. Please feel free to reach out if you're running into any other issues.
