### ISSUE TITLE
sentry_reinstall_backend assembly exception

### ISSUE THREAD

**Issue by flashup** [getsentry/sentry-unity#1864]
### Environment

How do you use Sentry?
Sentry self-hosted (22.10.0)

Which version of the SDK?
2.2.2

How did you install the package?
Git-URL

Which version of Unity?
2022.3.41f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Windows

### Steps to Reproduce

1. The error happens on application startup.

#### Callstack
```
System.EntryPointNotFoundException: sentry_reinstall_backend assembly:<unknown assembly> type:<unknown type> member:(null)
  Module "Sentry.Unity.Native.SentryNativeBridge", in ReinstallBackend
  Module "Sentry.Unity.Native.SentryNative", in ReinstallBackend
  Module "Sentry.Unity.SentryInitialization", in ReinstallBackend
```

#### Breadcrumbs
![Image](https://github.com/user-attachments/assets/1b502ed5-0646-4ebc-a28e-d79481293885)

**Comment by bruno-garcia** [comment]
Looks like `sentry.dll` is missing? That P/Invoke call is trying to call a function written in C on our native SDK.
This one:

https://github.com/getsentry/sentry-native/blob/66e5aae0ba472f80086cfa32466f054cffd5ce3d/src/sentry_core.c#L277

Looks like it can't find the DLL

**Comment by bruno-garcia** [comment]
> In the output dir I see the game.exe and the library game_Data/Managed/Sentry.dll

That's the managed (.NET) Sentry dll. We also provide a native DLL (`sentry.dll`). 

Seems to be a known issue:
* https://github.com/getsentry/sentry-unity/issues/1108

Native support for desktop targets IL2CPP so there might be a bug on Linux.


Does this crash the game or something? Or it's just an exception in the terminal/breadcrumb?
If the latter it might be a matter of skipping this call to`sentry_reinstall_backend`

Right now it load automatically:

https://github.com/getsentry/sentry-unity/blob/8c0967fedc553a2bd0f0ab95ece8b21b6c47e9d2/package-dev/Runtime/SentryInitialization.cs#L122-L131


Also relates to:
* https://github.com/getsentry/sentry-unity/issues/782

**Comment by flashup** [comment]
> That's the managed (.NET) Sentry dll. We also provide a native DLL (`sentry.dll`).

Ok, I also have this lib: `game_Data/Plugins/x86_64/sentry.dll`


> Does this crash the game or something?

Unfortunately, we couldn't reproduce this error. However, judging by the event logs, the error occurs for players every time they launch the game. Players continue to enter the game and trigger the error.

For players experiencing this issue, no other errors were found in the Sentry logs, so it seems that Sentry simply breaks at the start and doesn't work throughout the game session.

<details>
<summary>Events</summary>

![Image](https://github.com/user-attachments/assets/2e8f5152-b820-4c18-96d5-b9586dc4a33f)

</details>

> Does this crash the game or something? Or it's just an exception in the terminal/breadcrumb?

<details>
<summary>Event details</summary>

![Image](https://github.com/user-attachments/assets/4b9c888b-aaab-45f8-83c4-3c63918ea888)

</details>

**Comment by bruno-garcia** [comment]
> Ok, I also have this lib: game_Data/Plugins/x86_64/sentry.dll

That's the one! That doesn't seem available for some players. Maybe they copied the `.exe` somewhere else without copying the dlls? Or would the game not work at all if they did that? I wonder if we could statically link this instead, @vaind do you know? Since we're using crashpad it would not work anyway since we wouldn't have the handler around either.
For context, you should see `sentry.dll` as you pointed out, but also `crashpad_handler.exe` there which is needed to capture native crashes and create minidumps.

Regarding the events you see: it's C# exception thrown when trying to load, we capture that, but perhaps it disables the SDK after that then? looks like that at least if not other events come in (unless it's a coincidence). 

Could you verify that by deleting that DLL on your local build (game_Data/Plugins/x86_64/sentry.dll) and running the game? You should be able to see the same event in Sentry. Then you can try to create other events such as `SentrySdk.CaptureMessage`. I suspect it might just work out.

We should be able to catch that exception then, and continue running but without native crash support. At least you'll get all the C# errors, something like:
* https://github.com/getsentry/sentry-unity/issues/1864

**Comment by vaind** [comment]
> I wonder if we could statically link this instead

Not AFAIK. While we could create a statically linked library (.lib) and ship that, we build a game with static linking.


> We should be able to catch that exception then, and continue running but without native crash support.

I think we should try-catch this bit, right @bitsandfoxes?

https://github.com/getsentry/sentry-unity/blob/d66c8ab7dca1ca6aec35932272858e1c215ad710/package-dev/Runtime/SentryInitialization.cs#L126-L129

**Comment by bruno-garcia** [comment]
The PR with try/catch is here:

* https://github.com/getsentry/sentry-unity/pull/1895

The failure to load this should be taken into account before calling any P/Invoke method, otherwise those will fail too

**Comment by bitsandfoxes** [comment]
Fixed in https://github.com/getsentry/sentry-unity/pull/1898

**Comment by bruno-garcia** [comment]
> Fixed in [#1898](https://github.com/getsentry/sentry-unity/pull/1898)

Sorry this wasn't shipped yet.

We'll make a release soon.

**Comment by KrautApps** [comment]
Actually I still have that issue with 2.4.0.

**Comment by bruno-garcia** [comment]
@KrautApps could you please create a new issue and fill out the template?
What Unity version? Stack trace, etc. Any information that can help us debug this.
