### ISSUE TITLE
Consider reporting list of installed packages and version 

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#40]
The backend could help point out new versions or known issues with modules if they are included in events.

**Comment by semuserable** [comment]
This is [the official way](https://docs.unity3d.com/ScriptReference/PackageManager.Client.html?_ga=2.78712976.583230285.1615978892-456710978.1611564335).

Although, this API is asynchronous! and is inside `UnityEditor.dll`!. The gathering of info is done in `Sentry.Unity` (`UnityEventProcessor.cs`) which doesn't have reference to `UnityEditor.dll`. Should we change that because of that or try to find another way and not have reference to `UnityEditor.dll` from within `Sentry.Unity`?

**Comment by bruno-garcia** [comment]
> This is [the official way](https://docs.unity3d.com/ScriptReference/PackageManager.Client.html?_ga=2.78712976.583230285.1615978892-456710978.1611564335).
> 
> Although, this API is asynchronous! and inside `UnityEditor.dll`!. The gathering of info is done in `Sentry.Unity` (`UnityEventProcessor.cs`) which doesn't have reference to `UnityEditor.dll`. Should we change that or try to find another way and not have reference to `UnityEditor.dll` from within `Sentry.Unity`?

Can we do that at build time? Pass the list of stuff into some `ScriptableObject` that we read at runtime?

**Comment by bitsandfoxes** [comment]
With the config now being a scriptable object I guess now we easily can? Or we just create a second one and place it next to config?

**Comment by bitsandfoxes** [comment]
You're right: Dupe of https://github.com/getsentry/sentry-unity/issues/301
