### ISSUE TITLE
CSRF Verification Failed on http POST request, need to set `Referer` header

### ISSUE THREAD

**Issue by beerjamin** [getsentry/sentry-unity#403]
### Environment

How do you use Sentry?
self hosted instance 

Which SDK and version?
`Sentry 9.1.2` using https://github.com/getsentry/sentry-unity

### Steps to Reproduce

1. Send any event to sentry the sentry instance

### Expected Result

Event successfully sent

### Actual Result

Sentry: (Debug) Envelope  handed off to transport. #1 in queue.  (envelope never gets sent, queue keeps growing over time)

This problem only happens when using a self hosted sentry instance. I tested with a SaaS sentry instance and things run correctly. 

To give a bit more context to the issue, I am trying to sent sentry events from unity. The unity instance sends the events through a VPN configuration to a sentry self hosted instance. The HTTP Post request is not successful and I think the use case where the CSRF Verification Failed is not covered in the SDK code (maybe it should not be, but you dont actually get information why the failure happens).

However, when I do a post request myself, I see this result.

```
CSRF Verification Failed

A required security token was not found or was invalid.

If you're continually seeing this issue, try the following:

    Clear cookies (at least for Sentry's domain).
    Reload the page you're trying to submit (don't re-submit data).
    Re-enter the information, and submit the form again.

You are seeing this message because Sentry requires a 'Referer header' to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable 'Referer' headers, please re-enable them, at least for this site, or for HTTPS connections, or for 'same-origin' requests.
```

Now the question would be, should the client be able to set the `Referer` header? If yes, then this maybe would be better suited as a feature request. 
In case the client should not be able to set the `Referer` header and I am simply doing something wrong, any kind of suggestion is very appreciated.

**Comment by pavels** [comment]
Just got hit by this as well

Here is the relevant issue from other ruby library
https://github.com/getsentry/sentry-ruby/issues/1185

And here is the solution
https://github.com/getsentry/sentry-ruby/issues/1185#issuecomment-755441492

> in the new SDK we've switched the reporting endpoint from /store to /envelope, which requires 20.6.0 and above version if you use the on-premise installation.

I am on 9.1.2 as well - last version where i don't need to deal with the new pipeline

**Comment by bruno-garcia** [comment]
Sentry Unity SDK is not compatible with Sentry 9. Sentry introduced [Envelopes](https://develop.sentry.dev/sdk/envelopes/) which were added through [Relay](https://github.com/getsentry/relay). An ingestion service added after Sentry 9 was released. 

Many Sentry SDKs since then had major releases that rely on that endpoint and require Sentry v20.06 or higher. 
This SDK (which was developed this year) relies on Sentry .NET. The change that requires envelope came out on 3.0.0:

> Sentry On Premise Support
? This version uses the envelope endpoint. If you are using an on-premise installation it requires Sentry version >= v20.6.0 to work. If you are using sentry.io nothing will change and no action is needed.

[Release notes](https://github.com/getsentry/sentry-dotnet/releases/tag/3.0.0)

**Comment by beerjamin** [comment]
Thanks :beers:
