### ISSUE TITLE
Improve CI performance

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#449]
CI has been continuously built with a single/serial pipeline. That adds to the overall build time as we add new validations, etc.

The goal is to run in parallel what makes sense. And to avoid installing Unity on each run, which can be done with a customer Docker file on Linux:

![image](https://user-images.githubusercontent.com/1633368/144891294-e9abd194-1d2c-4ace-bfd2-4cbca779929b.png)

* [x] SDK split to separate jobs - #547
* [x] create a docker image for the linux build - https://github.com/getsentry/unity-docker
* [ ] prepare the package and run tests in a linux container
* [ ] build & smoke-test players on supported platforms

**Comment by lucas-zimerman** [comment]
@bruno-garcia  not sure how efficient this could be but what if we map a remote disk to Github actions and instead of installing Unity all the time, we just simply use the one that was installed on the remote disk?

**Comment by vaind** [comment]
@lucas-zimerman that's an interesting idea. If we could map a read-only drive from some cloud provider with the unity pre-installed that could be good. 

I was originally thinking about something similar - instead of using github cache (which isn't employed correctly because it constantly hits the size limit) - use a "manual" cache implementation, fetching pre-installed unity zip from AWS s3 bucket and extracting it (while streaming; GH cache seems to download, then extract). So that could be another option if the remote drive didn't work

**Comment by bruno-garcia** [comment]
Consider also: https://github.com/getsentry/sentry-unity/issues/312

**Comment by bruno-garcia** [comment]
@vaind seems like this issue can be closed?

**Comment by vaind** [comment]
> @vaind seems like this issue can be closed?

I'll still do some minor improvements here and there but yes, the overall goal of this issue seems fulfilled
