### ISSUE TITLE
Sentry Performance Monitor with Unity Project

### ISSUE THREAD

**Issue by Humoon** [getsentry/sentry-unity#502]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Win10 + UnityHub@2.5.6 + Unity@2020.3.23f1c1

### Steps to Reproduce

1. Installing Sentry Unity SDK using Unity Package Mananger.
2. Using Sentry.io to monitor the Unity Project performance.
3. Initialize ```SentryUnity```  in the Unity ```Start``` func, set the  ```TracesSampleRate``` to 1.0.
![image](https://user-images.githubusercontent.com/9549462/148046072-567b90ff-9c75-400f-820d-709cab7d502c.png)

4. Place the ```SentrySdk.StartTransaction``` inside the Unity ```Update``` func, where the FPS of Unity is 100. In other words, the Unity ```Update``` func constructs 100 transactions per secend and sends these transactions to Sentry.io.
![image](https://user-images.githubusercontent.com/9549462/148047591-884ca7ec-8dd8-4857-9e8a-97fc67f7f2a4.png)

5. Click the ```play``` to start game.

### Expected Result
The Sentry.io should capture 100 * 60 = 6000 transactions per minute.

### Actual Result
The Sentry.io captures about 600 transactions per minute from Unity Project.
![image](https://user-images.githubusercontent.com/9549462/148045135-90646559-fd3b-4a5d-a074-d749f558bebe.png)

I haven't found the relevant code in the source code yet,  and where can I find the dropped transactions ？

**Comment by lucas-zimerman** [comment]
Hi Humoon,

Does your org have Spike Protection enabled?

And to clarify, You might be sending too many requests in a short period of time and some of those might be getting blocked, you can validate that by enabling the Debug parameter on Sentry options.

And as a note, creating a transaction for every frame might deplete your quota in a short period of time, I would recommend not creating a transaction for every frame, you would get less spam if you would only finish the transactions that are slow for you.

**Comment by bruno-garcia** [comment]
The SDK is probably dropping these from it's in-memory queue as it's just creating more transactions than it can flush out over the network.
To be clear, this back pressure mechanism is there by design and will make sure the overhead caused by capturing events will be capped.

A transaction is designed to measure something meaninful, like a user operation. A game start, etc. A transaction is a unit billed at Sentry, you definitely don't want to capture a single transaction for each frame, on each game instance for each of your players.

You'd want to start a transaction when you start an operation you want to measure. Spans are added within that transaction to help you identify where time is spent, and bottlenecks.

There are examples here: https://github.com/getsentry/sentry-defenses

I hope this helps clarify things.

**Comment by Humoon** [comment]
Thanks for your replies. @lucas-zimerman @bruno-garcia 
I also tested this on my self-hosted/on-premise platform and the result is same as I expected, that is, the number of transactions created and sent by the Unity Project  is exactly the same as the number of Events reveived by Sentry.

(I set the Unity target FPS to 20.)
![image](https://user-images.githubusercontent.com/9549462/148198327-9715c2ec-f411-4f9b-9051-fade609dabc8.png)

Does this indicate that Sentry.io has certain limitation in some aspects, or other reasons.
