### ISSUE TITLE
[Regression] Sentry.h not found 

### ISSUE THREAD

**Issue by fahall** [getsentry/sentry-unity#588]
This appears to be a regression of #465 

### Environment

How do you use Sentry?
SaaS

Which version of the SDK?
0.10.1
0.11.0

Which version of Unity?
2020.3.25f1 LTS

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
During Build

### Steps to Reproduce
1. Upgrade Sentry Package via manifest from 0.9.2 to 0.10.1 or 0.11.0
2. Try to build using Github Action runner on Linux using [GameCI's Builder](https://game.ci/docs/github/builder).
3. Build fails

### Expected Result

Build should succeed (and does succeed when using 0.9.2). 

### Actual Result

Build Fails (see attached logs)

### Any logs or screenshots
[1_Deploy iOS  Deploy to Apple.txt](https://github.com/getsentry/sentry-unity/files/8137047/1_Deploy.iOS.Deploy.to.Apple.txt)
[1_Build iOS  Build with GameCI.txt](https://github.com/getsentry/sentry-unity/files/8137048/1_Build.iOS.Build.with.GameCI.txt)

**Comment by bruno-garcia** [comment]
We recently changed how the iOS Unity tools requirements outside of Windows:

Changelog entry:
https://github.com/getsentry/sentry-unity/blob/8e4a22cbef0a56ecac3cd3518efd918f8bf04fdc/CHANGELOG.md#fixes-1

Additional context in the PR: https://github.com/getsentry/sentry-unity/pull/559
And on the troubleshooting page:
https://docs.sentry.io/platforms/unity/troubleshooting/#sentryunityeditorios---systemreflectionreflectiontypeloadexception

This is about exporting an iOS project outside of a Mac for later building on a Mac. It's a game of cat and mouse, when we "fix" for one use case, we break the other.

**Comment by bruno-garcia** [comment]
Ideally we need some sort of warning here, when exporting an iOS build outside of a Mac. I believe @bitsandfoxes did something on the latest versions

**Comment by vaind** [comment]
I remember this being changed but it was always discussed as "when developers export iOS project on Windows". This was quite unlikely so only based on that it seems reasonable to make the change. However, the scenario OP is reporting is about building the app projects in CI, which is rather quite likely to be Linux (docker in this case). So maybe we should thing again if there's a way to support this while not forcing windows desktop users to install iOS build tools.

**Comment by fahall** [comment]
Yes, I'm running this using a pretty standard CI protocol for Unity. 

I would argue that supporting CI/CD pipelines is more important than not requiring that people install iOS build tools. We're talking a couple GB install per machine to install the iOS build tools? 

I don't know the technical details of why it's difficult, but it seems that there should be some way to make the CI/CD builds work conditioned on the iOS build tools being installed. Any pipeline to build for iOS is going to have them installed.

**Comment by bitsandfoxes** [comment]
Regardless of the iOS support being available: Adding Sentry to a project should never break a build and that's the aim of #592.

> I don't know the technical details of why it's difficult, but it seems that there should be some way to make the CI/CD builds work conditioned on the iOS build tools being installed. Any pipeline to build for iOS is going to have them installed.

There is. You'd have to embed the package in your project and set the platform settings of `Sentry.Unity.Editor.iOS.dll` to whichever platform your CI runs on.

The problem is: When the package gets installed via UPM it lives inside the Unity global package cache and we cannot modify any import-settings. So we've chosen to require the iOS module only on macOS by default, trying to create the least amount of friction for users. The idea is: "It's less annoying to have to enable a feature than it is to have builds break due to a feature you don't even want".

Sorry for the inconvenience, but until we find a solution we're chasing our tail here.
Maybe some editor window functionality where it automatically embeds the package for you and sets stuff correctly.
