### ISSUE TITLE
SDK names to indicate built for the Unity package

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-unity#616]
When investigating an event captured by the sentry-cocoa SDK, we inspect the event payload's `sdk.name` property. It says: `sentry.cocoa`. This doesn't help us tell apart the build done through submodule in this repository, packaged with the Unity SDK. That information can help us troubleshoot issues and understand adoption of the SDK (of iOS apps in general vs iOS+Unity).

There was a change in the sentry-native (https://github.com/getsentry/sentry-native/pull/677) to change its name (issue: https://github.com/getsentry/sentry-java/issues/1901) when building for Android. But that won't help us understand if that was a Unity Android build (packaged via this repo, UPM packaging).

The goal: Events captured by installing `sentry-unity` should report `sdk.name` as follows:

- [x] C# errors: `sentry.dotnet.unity`
- [x] Android: Java/Kotlin: `sentry.java.android.unity`
- [x] Android: C, C++: `sentry.native.android.unity`
- [x] iOS: Objective-C, Swift, C, C++: `sentry.cocoa.unity`
- [x] macOS: Objective-C, Swift, C, C++: `sentry.cocoa.unity`
- [x] Windows: C, C++: `sentry.native.unity`

**Comment by vaind** [comment]
Should we keep the version part of the SDK info as is, or use the Unity SDK version? Some pros & cons of both solutions - I'd say we should pass the Unity package version:

* unity SDK version everywhere: 
  - pro: makes it possible to identify which Unity package the issue comes from; in turn, we can then also tell which native SDK  version was used;
  - con: takes one more step to get to the native SDK version
* keep native SDK version:
  - pro: we know right away (without the additional lookup) which native SDK version issued this event
  - **con: no way to know which Unity package version was used**

**Comment by vaind** [comment]
The final piece: [the cocoa SDK PR](https://github.com/getsentry/sentry-cocoa/pull/1853) just got merged and released.
