### ISSUE TITLE
Tests don't run on fresh clone

### ISSUE THREAD

**Issue by Tyrrrz** [getsentry/sentry-unity#77]
Repro:

1. Clone repo
2. Open `unity-of-bugs` in Unity
3. Try to run tests and see them fail

This seems to happen because the following file gets invalidated due to the fact that `m_Script ... guid: <value>` changes:

https://github.com/getsentry/sentry-unity/blob/e574759ce085ff27646d7c9fa399082677d8e157/samples/unity-of-bugs/Assets/Resources/Sentry/SentryOptions.asset#L1-L23

Because of this, the DSN is effectively undefined and the code in tests doesn't function as it's supposed to.

It's unclear what `guid` corresponds to as the value Unity sets is not found anywhere else. That said, the guid seems to be consistent on the same machine.

Currently working around it with the following hack:

https://github.com/getsentry/sentry-unity/blob/73d9c1fd3e2049df5825c8feb2d8c6acff0c52fd/src/test/Sentry.Unity.Tests/PlayModeTests.cs#L14-L36

**Comment by bruno-garcia** [comment]
According to the investigation of @semuserable this happens because the type that's used as `ScriptableObject` is defined on an external assembly loaded into Unity instead of a Script in Unity built with it. Defining the type outside our project isn't an option unless we completely walk away from using a separate project so we're considering using plain json serialization and storing the file in the assets folder by ourslves (instead of using Unity Resources). @semuserable please correct me if I'm misunderstanding something

**Comment by semuserable** [comment]
@bruno-garcia yes, you're correct. Trying json ser/deser path currently.

**Comment by semuserable** [comment]
This one can be closed I assume?

**Comment by Tyrrrz** [comment]
@semuserable if you think it can be closed, then it can be closed ;)

**Comment by semuserable** [comment]
Re-tested, works as expected. Closing :)
